# Generated by Django 5.1.3 on 2024-11-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='apartment_number',
            field=models.CharField(max_length=10),
        ),
    ]
