# Generated by Django 5.1.3 on 2024-12-03 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_alter_visitor_apartment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='check_in',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
